config/routes.rb
Rails.application.routes.draw do
  resources :surveys do
    resources :questions, :only => [:create, :update, :destroy]
    get 'answers', on: :member
    get 'answers_of', on: :member
  end
  resources :participants
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'surveys#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :participant

  validates :content, presence: true, allow_blank: false
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/participant.rb
class Participant < ApplicationRecord
  has_many :answers, dependent: :destroy
  has_many :questions, through: :answers

  validates :name, presence: true, length: { minimum: 3, maximum: 100 }
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :survey
  has_many :answers, dependent: :destroy
  has_many :participants, through: :answers

  accepts_nested_attributes_for :answers,
    allow_destroy: true,
    reject_if: proc { |a| a['content'].blank? }

  validates :content, presence: true, allow_blank: false
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :questions, dependent: :destroy

  accepts_nested_attributes_for :questions

  validates :name, presence: true, length: { minimum: 3, maximum: 100 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: [:show, :edit, :update, :destroy]

  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(participant_params)

    respond_to do |format|
      if @participant.save
        format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1
  # PATCH/PUT /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant.destroy
    respond_to do |format|
      format.html { redirect_to participants_url, notice: 'Participant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participant_params
      params.require(:participant).permit(:name)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_survey, only: [:create]
  before_action :set_question, only: [:update, :destroy]

  # POST /surveys/7/questions
  def create
    @question = @survey.questions.create(question_params)

    notice =
      if @question.valid?
        "Question was successfully created."
      else
        "Question creation failed: #{@question.errors.full_messages.join("; ")}"
      end
    redirect_to edit_survey_path(@survey), notice: notice
  end

  # PATCH/PUT /surveys/7/questions/1
  def update
    notice =
      if @question.update(question_params)
        "Question was successfully updated."
      else
        "Question update failed: #{@question.errors.full_messages.join("; ")}"
      end
    redirect_to edit_survey_path(@survey), notice: notice
  end

  # DELETE /surveys/7/questions/1
  def destroy
    notice =
      if @question.destroy && @question.destroyed?
        "Question was successfully destroyed."
      else
        "Question destroy failed: #{@question.errors.full_messages.join("; ")}"
      end
    redirect_to edit_survey_path(@survey), notice: notice
  end

  private
    def set_survey
      @survey = Survey.find(params[:survey_id])
    end

    def set_question
      set_survey
      @question = @survey.questions.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:content)
    end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy, :answers, :answers_of]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
    @questions = @survey.questions
    @answers = @questions.inject({}) do |res,q|
      q.answers.each do |a|
        (res[a.participant_id] ||= {})[a.question_id] = a
      end
      res
    end
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to edit_survey_path(@survey), notice: 'Survey was successfully created.' }
        format.json { render :edit, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to edit_survey_path(@survey), notice: 'Survey was successfully updated.' }
        format.json { render :edit, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def answers
  end

  def answers_of
    @participant = params[:participant] && Participant.find(params[:participant])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    def survey_params
      survey_params_destroy_blank_answers(survey_params_validate)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params_validate
      params.require(:survey).permit(
        :name,
        :questions_attributes => [
          :id,
          :content,
          :answers_attributes => [
            :id,
            :content,
            :participant_id
          ]
        ]
      )
    end

    def survey_params_destroy_blank_answers(sparams)
      if sparams && sparams.include?(:questions_attributes)
        sparams[:questions_attributes].each do |qn, qparams|
          if qparams.include?(:answers_attributes)
            qparams[:answers_attributes].each do |an, aparams|
              aparams[:_destroy] = '1' if aparams.include?(:id) && aparams[:content].blank?
            end
          end
        end
      end
      sparams
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SurveyApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'Surveys', surveys_path %>
    |
    <%= link_to 'Paricipants', participants_path %>

    <hr>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/participants/_form.html.erb
<%= form_for(participant) do |f| %>
  <% if participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
      <% participant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/participants/edit.html.erb
<h1>Editing Participant</h1>

<%= render 'form', participant: @participant %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

app/views/participants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Participants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participants.each do |participant| %>
      <tr>
        <td><%= participant.name %></td>
        <td><%= link_to 'Show', participant %></td>
        <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
        <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Participant', new_participant_path %>

app/views/participants/new.html.erb
<h1>New Participant</h1>

<%= render 'form', participant: @participant %>

<%= link_to 'Back', participants_path %>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @participant.name %>
</p>

<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>

app/views/questions/_form.html.erb
<%= form_for [question.survey, question] do |f| %>
  <div class="field">
    <%= f.text_area :content, cols: 80, rows: 3 %>
  </div>
  <div class="action">
    <%= f.submit %>
    <%= link_to "Destroy Question", [question.survey, question],
                 method: :delete, class: "button_like",
                 data: { confirm: "Are you sure?" } %>
  </div>
<% end %>

app/views/questions/_question.html.erb
<li><%= question.content %></li>

app/views/surveys/_answers_of.html.erb
<%# form for editing the answers of the given survey and participant %>

<%= form_for(survey) do |f| %>
  <div class="survey_answers">
    <ol>
      <% survey.questions.each do |question| %>
        <li>
          <%= question.content %>
          <%= f.fields_for :questions, question do |q| %>
            <%= q.fields_for :answers, question.answers.find_or_initialize_by(participant_id: participant.id) do |a| %>
              <div class='survey_answer'><%= a.text_area :content %></div>
              <%= a.hidden_field :participant_id, :value => participant.id %>
            <% end %>
          <% end %>
        </li>
      <% end %>
    </ol>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/surveys/_form.html.erb
<%= form_for(survey) do |f| %>
  <% if survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, size: 80 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/surveys/answers.html.erb
<h1><%= @survey.name %> Answers</h1>
<br>
<h4>
  By
  <%=
    select_tag :participant_select,
               options_from_collection_for_select(Participant.all, :id, :name),
               prompt: "Please select a participant",
               post_link: answers_of_survey_path(@survey)
  %>
</h4>

<div id="survey_answers_of_participant">
</div>

<br>

<%= link_to 'Back', surveys_path %>

app/views/surveys/answers_of.js.erb
$("#survey_answers_of_participant").html("<%= j render "answers_of", survey: @survey, participant: @participant %>");

app/views/surveys/edit.html.erb
<p id="notice"><%= notice %></p>

<h1>Editing Survey</h1>

<%= render 'form', survey: @survey %>

<% unless @survey.questions.empty? %>
  <br>
  <h2> Questions </h2>
  <div class="survey_questions_edit">
    <ol>
      <% @survey.questions.each do |question| %>
        <li>
          <%= render 'questions/form', question: question %>
        </li>
      <% end %>
    </ol>
  </div>
<% end %>

<br>
<h2> Add question: </h2>
<div class="survey_questions_edit">
  <ul>
    <li>
      <%= render 'questions/form', question: @survey.questions.build %>
    </li>
  </ul>
</div>

<br>

<%= link_to 'Edit answers', answers_survey_path(@survey) %> |
<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Surveys</h1>

<br>

<table>
  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= survey.name %> (<%= pluralize(survey.questions.count, 'question') %>) </td>
        <td><%= link_to 'Show', survey %></td>
        <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
        <td><%= link_to 'Edit answers', answers_survey_path(survey) %></td>
        <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survey', new_survey_path %>

app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render 'form', survey: @survey %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <strong>Survey:</strong>
  <%= @survey.name %>
</h1>

<% unless @questions.empty? %>
  <br>
  <div class="survey_questions">
    <h2>Questions</h2>
    <ol>
      <%= render @questions %>
    </ol>
  </div>

  <% unless @answers.empty? %>
    <br>
    <div class="survey_answers">
      <h2>Answers</h2>
      <% @answers.each do |pid, q| %>
        <h4>Answers by <%= Participant.find(pid).name %></h4>
        <ol>
          <% q.each do |qid, a| %>
            <li>
              <%= @questions.find(qid).content %>
              <div class='survey_answer'><%= a.content %></div>
            </li>
          <% end %>
        </ol>
      <% end %>
    </div>
  <% end %>
<% end %>

<br>

<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Edit answers', answers_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>